# This workflow will build a .NET project and deploy to GitHub Pages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and GitHub Pages

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./04/04.csproj
    - name: Build
      run: dotnet build ./04/04.csproj --no-restore
    - name: Test
      run: dotnet test ./04/04.csproj --no-build --verbosity normal
    - name: Publish to GitHub Pages
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --output ./deploy/db.sql
        echo "dotnet-ef migrations script completed successfully."
      env:
        DOTNET_ROOT: ${{ github.workspace }}/deploy
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./04/04.csproj
